/*----------------------------------------------------------------------
 * This file is generated by mk_parser.py.
 *----------------------------------------------------------------------*/
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include "cparser.h"
#include "cparser_priv.h"
#include "cparser_token.h"
#include "cparser_tree.h"

cparser_result_t
cparser_glue_cnfg (cparser_t *parser)
{
    cparser_cmd_cnfg(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_cnfg_rule (cparser_t *parser)
{
    cparser_cmd_cnfg_rule(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_rule_add_action_version_proto_sip_sprt_direction_dip_dprt (cparser_t *parser)
{
    char *action_val;
    char **action_ptr = NULL;
    char *version_val;
    char **version_ptr = NULL;
    char *proto_val;
    char **proto_ptr = NULL;
    uint32_t sip_val;
    uint32_t *sip_ptr = NULL;
    uint32_t sprt_val;
    uint32_t *sprt_ptr = NULL;
    char *direction_val;
    char **direction_ptr = NULL;
    uint32_t dip_val;
    uint32_t *dip_ptr = NULL;
    uint32_t dprt_val;
    uint32_t *dprt_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_list(&parser->tokens[1], &action_val);
    assert(CPARSER_OK == rc);
    action_ptr = &action_val;
    rc = cparser_get_list(&parser->tokens[2], &version_val);
    assert(CPARSER_OK == rc);
    version_ptr = &version_val;
    rc = cparser_get_list(&parser->tokens[3], &proto_val);
    assert(CPARSER_OK == rc);
    proto_ptr = &proto_val;
    rc = cparser_get_ipv4addr(&parser->tokens[4], &sip_val);
    assert(CPARSER_OK == rc);
    sip_ptr = &sip_val;
    rc = cparser_get_uint(&parser->tokens[5], &sprt_val);
    assert(CPARSER_OK == rc);
    sprt_ptr = &sprt_val;
    rc = cparser_get_list(&parser->tokens[6], &direction_val);
    assert(CPARSER_OK == rc);
    direction_ptr = &direction_val;
    rc = cparser_get_ipv4addr(&parser->tokens[7], &dip_val);
    assert(CPARSER_OK == rc);
    dip_ptr = &dip_val;
    rc = cparser_get_uint(&parser->tokens[8], &dprt_val);
    assert(CPARSER_OK == rc);
    dprt_ptr = &dprt_val;
    cparser_cmd_rule_add_action_version_proto_sip_sprt_direction_dip_dprt(&parser->context,
        action_ptr,
        version_ptr,
        proto_ptr,
        sip_ptr,
        sprt_ptr,
        direction_ptr,
        dip_ptr,
        dprt_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_rule_lst (cparser_t *parser)
{
    cparser_cmd_rule_lst(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_lst_tcp (cparser_t *parser)
{
    cparser_cmd_lst_tcp(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_lst_udp (cparser_t *parser)
{
    cparser_cmd_lst_udp(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_lst_ssl (cparser_t *parser)
{
    cparser_cmd_lst_ssl(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_lst_icmp (cparser_t *parser)
{
    cparser_cmd_lst_icmp(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_lst_http (cparser_t *parser)
{
    cparser_cmd_lst_http(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_lst_tls (cparser_t *parser)
{
    cparser_cmd_lst_tls(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_lst_gre (cparser_t *parser)
{
    cparser_cmd_lst_gre(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_lst_gtp (cparser_t *parser)
{
    cparser_cmd_lst_gtp(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_lst_ftp (cparser_t *parser)
{
    cparser_cmd_lst_ftp(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_lst_sctp (cparser_t *parser)
{
    cparser_cmd_lst_sctp(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_lst_smtp (cparser_t *parser)
{
    cparser_cmd_lst_smtp(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_lst_dns (cparser_t *parser)
{
    cparser_cmd_lst_dns(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_lst_smb (cparser_t *parser)
{
    cparser_cmd_lst_smb(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_lst_smb2 (cparser_t *parser)
{
    cparser_cmd_lst_smb2(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_lst_dcerpc (cparser_t *parser)
{
    cparser_cmd_lst_dcerpc(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_lst_clr (cparser_t *parser)
{
    cparser_cmd_lst_clr(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_lst_exit (cparser_t *parser)
{
    cparser_cmd_lst_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_rule_del_version_proto_rule_num (cparser_t *parser)
{
    char *version_val;
    char **version_ptr = NULL;
    char *proto_val;
    char **proto_ptr = NULL;
    uint32_t rule_num_val;
    uint32_t *rule_num_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_list(&parser->tokens[1], &version_val);
    assert(CPARSER_OK == rc);
    version_ptr = &version_val;
    rc = cparser_get_list(&parser->tokens[2], &proto_val);
    assert(CPARSER_OK == rc);
    proto_ptr = &proto_val;
    rc = cparser_get_uint(&parser->tokens[3], &rule_num_val);
    assert(CPARSER_OK == rc);
    rule_num_ptr = &rule_num_val;
    cparser_cmd_rule_del_version_proto_rule_num(&parser->context,
        version_ptr,
        proto_ptr,
        rule_num_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_rule_clr (cparser_t *parser)
{
    cparser_cmd_rule_clr(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_rule_exit (cparser_t *parser)
{
    cparser_cmd_rule_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_cnfg_mode_mode (cparser_t *parser)
{
    char *mode_val;
    char **mode_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_list(&parser->tokens[1], &mode_val);
    assert(CPARSER_OK == rc);
    mode_ptr = &mode_val;
    cparser_cmd_cnfg_mode_mode(&parser->context,
        mode_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_cnfg_port_ingress_port (cparser_t *parser)
{
    char *ingress_val;
    char **ingress_ptr = NULL;
    uint32_t port_val;
    uint32_t *port_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_list(&parser->tokens[1], &ingress_val);
    assert(CPARSER_OK == rc);
    ingress_ptr = &ingress_val;
    rc = cparser_get_uint(&parser->tokens[2], &port_val);
    assert(CPARSER_OK == rc);
    port_ptr = &port_val;
    cparser_cmd_cnfg_port_ingress_port(&parser->context,
        ingress_ptr,
        port_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_cnfg_pact (cparser_t *parser)
{
    cparser_cmd_cnfg_pact(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_pact_port1 (cparser_t *parser)
{
    cparser_cmd_pact_port1(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port1_fdrp_fdrp (cparser_t *parser)
{
    uint32_t fdrp_val;
    uint32_t *fdrp_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &fdrp_val);
    assert(CPARSER_OK == rc);
    fdrp_ptr = &fdrp_val;
    cparser_cmd_port1_fdrp_fdrp(&parser->context,
        fdrp_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port1_drop_drp (cparser_t *parser)
{
    uint32_t drp_val;
    uint32_t *drp_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &drp_val);
    assert(CPARSER_OK == rc);
    drp_ptr = &drp_val;
    cparser_cmd_port1_drop_drp(&parser->context,
        drp_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port1_acl_acl (cparser_t *parser)
{
    uint32_t acl_val;
    uint32_t *acl_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &acl_val);
    assert(CPARSER_OK == rc);
    acl_ptr = &acl_val;
    cparser_cmd_port1_acl_acl(&parser->context,
        acl_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port1_st_st (cparser_t *parser)
{
    uint32_t st_val;
    uint32_t *st_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &st_val);
    assert(CPARSER_OK == rc);
    st_ptr = &st_val;
    cparser_cmd_port1_st_st(&parser->context,
        st_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port1_clr (cparser_t *parser)
{
    cparser_cmd_port1_clr(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port1_exit (cparser_t *parser)
{
    cparser_cmd_port1_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_pact_port2 (cparser_t *parser)
{
    cparser_cmd_pact_port2(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port2_fdrp_fdrp (cparser_t *parser)
{
    uint32_t fdrp_val;
    uint32_t *fdrp_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &fdrp_val);
    assert(CPARSER_OK == rc);
    fdrp_ptr = &fdrp_val;
    cparser_cmd_port2_fdrp_fdrp(&parser->context,
        fdrp_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port2_drop_drp (cparser_t *parser)
{
    uint32_t drp_val;
    uint32_t *drp_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &drp_val);
    assert(CPARSER_OK == rc);
    drp_ptr = &drp_val;
    cparser_cmd_port2_drop_drp(&parser->context,
        drp_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port2_acl_acl (cparser_t *parser)
{
    uint32_t acl_val;
    uint32_t *acl_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &acl_val);
    assert(CPARSER_OK == rc);
    acl_ptr = &acl_val;
    cparser_cmd_port2_acl_acl(&parser->context,
        acl_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port2_st_st (cparser_t *parser)
{
    uint32_t st_val;
    uint32_t *st_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &st_val);
    assert(CPARSER_OK == rc);
    st_ptr = &st_val;
    cparser_cmd_port2_st_st(&parser->context,
        st_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port2_clr (cparser_t *parser)
{
    cparser_cmd_port2_clr(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port2_exit (cparser_t *parser)
{
    cparser_cmd_port2_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_pact_port3 (cparser_t *parser)
{
    cparser_cmd_pact_port3(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port3_fdrp_fdrp (cparser_t *parser)
{
    uint32_t fdrp_val;
    uint32_t *fdrp_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &fdrp_val);
    assert(CPARSER_OK == rc);
    fdrp_ptr = &fdrp_val;
    cparser_cmd_port3_fdrp_fdrp(&parser->context,
        fdrp_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port3_drop_drp (cparser_t *parser)
{
    uint32_t drp_val;
    uint32_t *drp_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &drp_val);
    assert(CPARSER_OK == rc);
    drp_ptr = &drp_val;
    cparser_cmd_port3_drop_drp(&parser->context,
        drp_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port3_acl_acl (cparser_t *parser)
{
    uint32_t acl_val;
    uint32_t *acl_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &acl_val);
    assert(CPARSER_OK == rc);
    acl_ptr = &acl_val;
    cparser_cmd_port3_acl_acl(&parser->context,
        acl_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port3_st_st (cparser_t *parser)
{
    uint32_t st_val;
    uint32_t *st_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &st_val);
    assert(CPARSER_OK == rc);
    st_ptr = &st_val;
    cparser_cmd_port3_st_st(&parser->context,
        st_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port3_clr (cparser_t *parser)
{
    cparser_cmd_port3_clr(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port3_exit (cparser_t *parser)
{
    cparser_cmd_port3_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_pact_port4 (cparser_t *parser)
{
    cparser_cmd_pact_port4(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port4_fdrp_fdrp (cparser_t *parser)
{
    uint32_t fdrp_val;
    uint32_t *fdrp_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &fdrp_val);
    assert(CPARSER_OK == rc);
    fdrp_ptr = &fdrp_val;
    cparser_cmd_port4_fdrp_fdrp(&parser->context,
        fdrp_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port4_drop_drp (cparser_t *parser)
{
    uint32_t drp_val;
    uint32_t *drp_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &drp_val);
    assert(CPARSER_OK == rc);
    drp_ptr = &drp_val;
    cparser_cmd_port4_drop_drp(&parser->context,
        drp_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port4_acl_acl (cparser_t *parser)
{
    uint32_t acl_val;
    uint32_t *acl_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &acl_val);
    assert(CPARSER_OK == rc);
    acl_ptr = &acl_val;
    cparser_cmd_port4_acl_acl(&parser->context,
        acl_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port4_st_st (cparser_t *parser)
{
    uint32_t st_val;
    uint32_t *st_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &st_val);
    assert(CPARSER_OK == rc);
    st_ptr = &st_val;
    cparser_cmd_port4_st_st(&parser->context,
        st_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port4_clr (cparser_t *parser)
{
    cparser_cmd_port4_clr(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_port4_exit (cparser_t *parser)
{
    cparser_cmd_port4_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_pact_clr (cparser_t *parser)
{
    cparser_cmd_pact_clr(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_pact_exit (cparser_t *parser)
{
    cparser_cmd_pact_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_cnfg_clr (cparser_t *parser)
{
    cparser_cmd_cnfg_clr(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_cnfg_exit (cparser_t *parser)
{
    cparser_cmd_cnfg_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show (cparser_t *parser)
{
    cparser_cmd_show(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_rule (cparser_t *parser)
{
    cparser_cmd_show_rule(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_rule1_info (cparser_t *parser)
{
    cparser_cmd_rule1_info(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_rule1_dtls (cparser_t *parser)
{
    cparser_cmd_rule1_dtls(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_details_tcp (cparser_t *parser)
{
    cparser_cmd_details_tcp(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_details_udp (cparser_t *parser)
{
    cparser_cmd_details_udp(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_details_icmp (cparser_t *parser)
{
    cparser_cmd_details_icmp(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_details_http (cparser_t *parser)
{
    cparser_cmd_details_http(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_details_ssl (cparser_t *parser)
{
    cparser_cmd_details_ssl(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_details_tls (cparser_t *parser)
{
    cparser_cmd_details_tls(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_details_gre (cparser_t *parser)
{
    cparser_cmd_details_gre(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_details_gtp (cparser_t *parser)
{
    cparser_cmd_details_gtp(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_details_ftp (cparser_t *parser)
{
    cparser_cmd_details_ftp(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_details_sctp (cparser_t *parser)
{
    cparser_cmd_details_sctp(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_details_smtp (cparser_t *parser)
{
    cparser_cmd_details_smtp(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_details_dns (cparser_t *parser)
{
    cparser_cmd_details_dns(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_details_smb (cparser_t *parser)
{
    cparser_cmd_details_smb(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_details_smb2 (cparser_t *parser)
{
    cparser_cmd_details_smb2(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_details_dcerpc (cparser_t *parser)
{
    cparser_cmd_details_dcerpc(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_details_clr (cparser_t *parser)
{
    cparser_cmd_details_clr(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_details_exit (cparser_t *parser)
{
    cparser_cmd_details_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_rule1_clr (cparser_t *parser)
{
    cparser_cmd_rule1_clr(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_rule1_exit (cparser_t *parser)
{
    cparser_cmd_rule1_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_mode (cparser_t *parser)
{
    cparser_cmd_show_mode(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_port (cparser_t *parser)
{
    cparser_cmd_show_port(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_pact (cparser_t *parser)
{
    cparser_cmd_show_pact(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_intf (cparser_t *parser)
{
    cparser_cmd_show_intf(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_intf_info_intf (cparser_t *parser)
{
    uint32_t intf_val;
    uint32_t *intf_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &intf_val);
    assert(CPARSER_OK == rc);
    intf_ptr = &intf_val;
    cparser_cmd_intf_info_intf(&parser->context,
        intf_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_intf_stat_num (cparser_t *parser)
{
    uint32_t num_val;
    uint32_t *num_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &num_val);
    assert(CPARSER_OK == rc);
    num_ptr = &num_val;
    cparser_cmd_intf_stat_num(&parser->context,
        num_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_intf_clr (cparser_t *parser)
{
    cparser_cmd_intf_clr(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_intf_exit (cparser_t *parser)
{
    cparser_cmd_intf_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_stat (cparser_t *parser)
{
    cparser_cmd_show_stat(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_stat_app (cparser_t *parser)
{
    cparser_cmd_stat_app(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_cont_flow (cparser_t *parser)
{
    cparser_cmd_cont_flow(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_cont_dcdr (cparser_t *parser)
{
    cparser_cmd_cont_dcdr(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_cont_tcp (cparser_t *parser)
{
    cparser_cmd_cont_tcp(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_cont_dfrg (cparser_t *parser)
{
    cparser_cmd_cont_dfrg(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_cont_dtct (cparser_t *parser)
{
    cparser_cmd_cont_dtct(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_cont_err (cparser_t *parser)
{
    cparser_cmd_cont_err(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_cont_clr (cparser_t *parser)
{
    cparser_cmd_cont_clr(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_cont_exit (cparser_t *parser)
{
    cparser_cmd_cont_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_stat_rxfp (cparser_t *parser)
{
    cparser_cmd_stat_rxfp(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_stat_st1 (cparser_t *parser)
{
    cparser_cmd_stat_st1(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_stat_st2 (cparser_t *parser)
{
    cparser_cmd_stat_st2(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_stat_txfw (cparser_t *parser)
{
    cparser_cmd_stat_txfw(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_stat_clr (cparser_t *parser)
{
    cparser_cmd_stat_clr(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_stat_exit (cparser_t *parser)
{
    cparser_cmd_stat_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_clr (cparser_t *parser)
{
    cparser_cmd_show_clr(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_exit (cparser_t *parser)
{
    cparser_cmd_show_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_clr (cparser_t *parser)
{
    cparser_cmd_clr(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_quit (cparser_t *parser)
{
    cparser_cmd_quit(&parser->context);
    return CPARSER_OK;
}

cparser_node_t cparser_node_quit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_quit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_quit = {
    CPARSER_NODE_KEYWORD,
    0,
    "quit",
    "exit from application",
    NULL,
    &cparser_node_quit_eol
};

cparser_node_t cparser_node_clr_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_clr,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_clr = {
    CPARSER_NODE_KEYWORD,
    0,
    "clr ",
    "clear screen",
    &cparser_node_quit,
    &cparser_node_clr_eol
};

cparser_node_t cparser_node_show_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_exit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    "exit from show sub-context",
    NULL,
    &cparser_node_show_root_exit_eol
};

cparser_node_t cparser_node_show_root_clr_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_clr,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_root_clr = {
    CPARSER_NODE_KEYWORD,
    0,
    "clr ",
    "clear screen",
    &cparser_node_show_root_exit,
    &cparser_node_show_root_clr_eol
};

cparser_node_t cparser_node_show_stat_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_stat_exit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_stat_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit ",
    "exit from stat sub-context",
    NULL,
    &cparser_node_show_stat_root_exit_eol
};

cparser_node_t cparser_node_show_stat_root_clr_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_stat_clr,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_stat_root_clr = {
    CPARSER_NODE_KEYWORD,
    0,
    "clr  ",
    "clear screen",
    &cparser_node_show_stat_root_exit,
    &cparser_node_show_stat_root_clr_eol
};

cparser_node_t cparser_node_show_stat_root_txfw_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_stat_txfw,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_stat_root_txfw = {
    CPARSER_NODE_KEYWORD,
    0,
    "txfw ",
    "TX-FW stats",
    &cparser_node_show_stat_root_clr,
    &cparser_node_show_stat_root_txfw_eol
};

cparser_node_t cparser_node_show_stat_root_st2_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_stat_st2,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_stat_root_st2 = {
    CPARSER_NODE_KEYWORD,
    0,
    "st2  ",
    "Suricata thread2 stats",
    &cparser_node_show_stat_root_txfw,
    &cparser_node_show_stat_root_st2_eol
};

cparser_node_t cparser_node_show_stat_root_st1_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_stat_st1,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_stat_root_st1 = {
    CPARSER_NODE_KEYWORD,
    0,
    "st1  ",
    "Suricata thread1 stats",
    &cparser_node_show_stat_root_st2,
    &cparser_node_show_stat_root_st1_eol
};

cparser_node_t cparser_node_show_stat_root_rxfp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_stat_rxfp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_stat_root_rxfp = {
    CPARSER_NODE_KEYWORD,
    0,
    "rxfp",
    "rxfp stats",
    &cparser_node_show_stat_root_st1,
    &cparser_node_show_stat_root_rxfp_eol
};

cparser_node_t cparser_node_stat_app_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_cont_exit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_stat_app_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    "exit from app sub-context",
    NULL,
    &cparser_node_stat_app_root_exit_eol
};

cparser_node_t cparser_node_stat_app_root_clr_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_cont_clr,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_stat_app_root_clr = {
    CPARSER_NODE_KEYWORD,
    0,
    "clr ",
    "clear screen",
    &cparser_node_stat_app_root_exit,
    &cparser_node_stat_app_root_clr_eol
};

cparser_node_t cparser_node_stat_app_root_err_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_cont_err,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_stat_app_root_err = {
    CPARSER_NODE_KEYWORD,
    0,
    "err ",
    "Error stats",
    &cparser_node_stat_app_root_clr,
    &cparser_node_stat_app_root_err_eol
};

cparser_node_t cparser_node_stat_app_root_dtct_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_cont_dtct,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_stat_app_root_dtct = {
    CPARSER_NODE_KEYWORD,
    0,
    "dtct",
    "detect related stats",
    &cparser_node_stat_app_root_err,
    &cparser_node_stat_app_root_dtct_eol
};

cparser_node_t cparser_node_stat_app_root_dfrg_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_cont_dfrg,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_stat_app_root_dfrg = {
    CPARSER_NODE_KEYWORD,
    0,
    "dfrg",
    "defrag related stats",
    &cparser_node_stat_app_root_dtct,
    &cparser_node_stat_app_root_dfrg_eol
};

cparser_node_t cparser_node_stat_app_root_tcp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_cont_tcp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_stat_app_root_tcp = {
    CPARSER_NODE_KEYWORD,
    0,
    "tcp ",
    "tcp related stats",
    &cparser_node_stat_app_root_dfrg,
    &cparser_node_stat_app_root_tcp_eol
};

cparser_node_t cparser_node_stat_app_root_dcdr_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_cont_dcdr,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_stat_app_root_dcdr = {
    CPARSER_NODE_KEYWORD,
    0,
    "dcdr",
    "decoder related stats",
    &cparser_node_stat_app_root_tcp,
    &cparser_node_stat_app_root_dcdr_eol
};

cparser_node_t cparser_node_stat_app_root_flow_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_cont_flow,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_stat_app_root_flow = {
    CPARSER_NODE_KEYWORD,
    0,
    "flow",
    "flow related stats",
    &cparser_node_stat_app_root_dcdr,
    &cparser_node_stat_app_root_flow_eol
};

cparser_node_t cparser_node_stat_app_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode cont",
    NULL,
    &cparser_node_stat_app_root_flow
};

cparser_node_t cparser_node_show_stat_root_app_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_stat_app,
    NULL,
    NULL,
    &cparser_node_stat_app_root
};

cparser_node_t cparser_node_show_stat_root_app = {
    CPARSER_NODE_KEYWORD,
    0,
    "app  ",
    "display counters",
    &cparser_node_show_stat_root_rxfp,
    &cparser_node_show_stat_root_app_eol
};

cparser_node_t cparser_node_show_stat_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode stat",
    NULL,
    &cparser_node_show_stat_root_app
};

cparser_node_t cparser_node_show_root_stat_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_stat,
    NULL,
    NULL,
    &cparser_node_show_stat_root
};

cparser_node_t cparser_node_show_root_stat = {
    CPARSER_NODE_KEYWORD,
    0,
    "stat",
    "display stats",
    &cparser_node_show_root_clr,
    &cparser_node_show_root_stat_eol
};

cparser_node_t cparser_node_show_intf_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_intf_exit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_intf_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    "exit from interface sub-context",
    NULL,
    &cparser_node_show_intf_root_exit_eol
};

cparser_node_t cparser_node_show_intf_root_clr_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_intf_clr,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_intf_root_clr = {
    CPARSER_NODE_KEYWORD,
    0,
    "clr ",
    "clear screen",
    &cparser_node_show_intf_root_exit,
    &cparser_node_show_intf_root_clr_eol
};

cparser_node_t cparser_node_show_intf_root_stat_num_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_intf_stat_num,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_intf_root_stat_num = {
    CPARSER_NODE_UINT,
    0,
    "interface number 0-4",
    "0 represents all",
    NULL,
    &cparser_node_show_intf_root_stat_num_eol
};

cparser_node_t cparser_node_show_intf_root_stat = {
    CPARSER_NODE_KEYWORD,
    0,
    "stat",
    "interface stats",
    &cparser_node_show_intf_root_clr,
    &cparser_node_show_intf_root_stat_num
};

cparser_node_t cparser_node_show_intf_root_info_intf_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_intf_info_intf,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_intf_root_info_intf = {
    CPARSER_NODE_UINT,
    0,
    "port1 - 1|port2 - 2|port3 - 3|port4 - 4| all -0",
    NULL,
    NULL,
    &cparser_node_show_intf_root_info_intf_eol
};

cparser_node_t cparser_node_show_intf_root_info = {
    CPARSER_NODE_KEYWORD,
    0,
    "info",
    "interface info",
    &cparser_node_show_intf_root_stat,
    &cparser_node_show_intf_root_info_intf
};

cparser_node_t cparser_node_show_intf_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode intf",
    NULL,
    &cparser_node_show_intf_root_info
};

cparser_node_t cparser_node_show_root_intf_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_intf,
    NULL,
    NULL,
    &cparser_node_show_intf_root
};

cparser_node_t cparser_node_show_root_intf = {
    CPARSER_NODE_KEYWORD,
    0,
    "intf",
    "interface details",
    &cparser_node_show_root_stat,
    &cparser_node_show_root_intf_eol
};

cparser_node_t cparser_node_show_root_pact_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_pact,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_root_pact = {
    CPARSER_NODE_KEYWORD,
    0,
    "pact",
    "port action",
    &cparser_node_show_root_intf,
    &cparser_node_show_root_pact_eol
};

cparser_node_t cparser_node_show_root_port_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_port,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_root_port = {
    CPARSER_NODE_KEYWORD,
    0,
    "port",
    "port info",
    &cparser_node_show_root_pact,
    &cparser_node_show_root_port_eol
};

cparser_node_t cparser_node_show_root_mode_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_mode,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_root_mode = {
    CPARSER_NODE_KEYWORD,
    0,
    "mode",
    "display mode",
    &cparser_node_show_root_port,
    &cparser_node_show_root_mode_eol
};

cparser_node_t cparser_node_show_rule_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_rule1_exit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_rule_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    "exit from rule sub-context",
    NULL,
    &cparser_node_show_rule_root_exit_eol
};

cparser_node_t cparser_node_show_rule_root_clr_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_rule1_clr,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_rule_root_clr = {
    CPARSER_NODE_KEYWORD,
    0,
    "clr ",
    "clear screen",
    &cparser_node_show_rule_root_exit,
    &cparser_node_show_rule_root_clr_eol
};

cparser_node_t cparser_node_rule1_dtls_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_details_exit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule1_dtls_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    "exit from rule sub-context",
    NULL,
    &cparser_node_rule1_dtls_root_exit_eol
};

cparser_node_t cparser_node_rule1_dtls_root_clr_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_details_clr,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule1_dtls_root_clr = {
    CPARSER_NODE_KEYWORD,
    0,
    "clr ",
    "clear screen",
    &cparser_node_rule1_dtls_root_exit,
    &cparser_node_rule1_dtls_root_clr_eol
};

cparser_node_t cparser_node_rule1_dtls_root_dcerpc_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_details_dcerpc,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule1_dtls_root_dcerpc = {
    CPARSER_NODE_KEYWORD,
    0,
    "dcerpc",
    "dcerpc rule",
    &cparser_node_rule1_dtls_root_clr,
    &cparser_node_rule1_dtls_root_dcerpc_eol
};

cparser_node_t cparser_node_rule1_dtls_root_smb2_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_details_smb2,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule1_dtls_root_smb2 = {
    CPARSER_NODE_KEYWORD,
    0,
    "smb2  ",
    "smb2 rule",
    &cparser_node_rule1_dtls_root_dcerpc,
    &cparser_node_rule1_dtls_root_smb2_eol
};

cparser_node_t cparser_node_rule1_dtls_root_smb_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_details_smb,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule1_dtls_root_smb = {
    CPARSER_NODE_KEYWORD,
    0,
    "smb   ",
    "smb rule",
    &cparser_node_rule1_dtls_root_smb2,
    &cparser_node_rule1_dtls_root_smb_eol
};

cparser_node_t cparser_node_rule1_dtls_root_dns_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_details_dns,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule1_dtls_root_dns = {
    CPARSER_NODE_KEYWORD,
    0,
    "dns   ",
    "dns rule",
    &cparser_node_rule1_dtls_root_smb,
    &cparser_node_rule1_dtls_root_dns_eol
};

cparser_node_t cparser_node_rule1_dtls_root_smtp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_details_smtp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule1_dtls_root_smtp = {
    CPARSER_NODE_KEYWORD,
    0,
    "smtp  ",
    "smtp rule",
    &cparser_node_rule1_dtls_root_dns,
    &cparser_node_rule1_dtls_root_smtp_eol
};

cparser_node_t cparser_node_rule1_dtls_root_sctp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_details_sctp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule1_dtls_root_sctp = {
    CPARSER_NODE_KEYWORD,
    0,
    "sctp  ",
    "sctp rule",
    &cparser_node_rule1_dtls_root_smtp,
    &cparser_node_rule1_dtls_root_sctp_eol
};

cparser_node_t cparser_node_rule1_dtls_root_ftp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_details_ftp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule1_dtls_root_ftp = {
    CPARSER_NODE_KEYWORD,
    0,
    "ftp   ",
    "ftp rule",
    &cparser_node_rule1_dtls_root_sctp,
    &cparser_node_rule1_dtls_root_ftp_eol
};

cparser_node_t cparser_node_rule1_dtls_root_gtp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_details_gtp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule1_dtls_root_gtp = {
    CPARSER_NODE_KEYWORD,
    0,
    "gtp   ",
    "gtp rule",
    &cparser_node_rule1_dtls_root_ftp,
    &cparser_node_rule1_dtls_root_gtp_eol
};

cparser_node_t cparser_node_rule1_dtls_root_gre_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_details_gre,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule1_dtls_root_gre = {
    CPARSER_NODE_KEYWORD,
    0,
    "gre   ",
    "gre rule",
    &cparser_node_rule1_dtls_root_gtp,
    &cparser_node_rule1_dtls_root_gre_eol
};

cparser_node_t cparser_node_rule1_dtls_root_tls_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_details_tls,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule1_dtls_root_tls = {
    CPARSER_NODE_KEYWORD,
    0,
    "tls   ",
    "tls rule",
    &cparser_node_rule1_dtls_root_gre,
    &cparser_node_rule1_dtls_root_tls_eol
};

cparser_node_t cparser_node_rule1_dtls_root_ssl_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_details_ssl,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule1_dtls_root_ssl = {
    CPARSER_NODE_KEYWORD,
    0,
    "ssl   ",
    "ssl rule",
    &cparser_node_rule1_dtls_root_tls,
    &cparser_node_rule1_dtls_root_ssl_eol
};

cparser_node_t cparser_node_rule1_dtls_root_http_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_details_http,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule1_dtls_root_http = {
    CPARSER_NODE_KEYWORD,
    0,
    "http  ",
    "http rule",
    &cparser_node_rule1_dtls_root_ssl,
    &cparser_node_rule1_dtls_root_http_eol
};

cparser_node_t cparser_node_rule1_dtls_root_icmp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_details_icmp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule1_dtls_root_icmp = {
    CPARSER_NODE_KEYWORD,
    0,
    "icmp  ",
    "icmp rule",
    &cparser_node_rule1_dtls_root_http,
    &cparser_node_rule1_dtls_root_icmp_eol
};

cparser_node_t cparser_node_rule1_dtls_root_udp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_details_udp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule1_dtls_root_udp = {
    CPARSER_NODE_KEYWORD,
    0,
    "udp   ",
    "udp rule",
    &cparser_node_rule1_dtls_root_icmp,
    &cparser_node_rule1_dtls_root_udp_eol
};

cparser_node_t cparser_node_rule1_dtls_root_tcp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_details_tcp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule1_dtls_root_tcp = {
    CPARSER_NODE_KEYWORD,
    0,
    "tcp   ",
    "tcp rule",
    &cparser_node_rule1_dtls_root_udp,
    &cparser_node_rule1_dtls_root_tcp_eol
};

cparser_node_t cparser_node_rule1_dtls_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode details",
    NULL,
    &cparser_node_rule1_dtls_root_tcp
};

cparser_node_t cparser_node_show_rule_root_dtls_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_rule1_dtls,
    NULL,
    NULL,
    &cparser_node_rule1_dtls_root
};

cparser_node_t cparser_node_show_rule_root_dtls = {
    CPARSER_NODE_KEYWORD,
    0,
    "dtls",
    "rule details",
    &cparser_node_show_rule_root_clr,
    &cparser_node_show_rule_root_dtls_eol
};

cparser_node_t cparser_node_show_rule_root_info_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_rule1_info,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_rule_root_info = {
    CPARSER_NODE_KEYWORD,
    0,
    "info",
    "rule info",
    &cparser_node_show_rule_root_dtls,
    &cparser_node_show_rule_root_info_eol
};

cparser_node_t cparser_node_show_rule_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode rule1",
    NULL,
    &cparser_node_show_rule_root_info
};

cparser_node_t cparser_node_show_root_rule_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_rule,
    NULL,
    NULL,
    &cparser_node_show_rule_root
};

cparser_node_t cparser_node_show_root_rule = {
    CPARSER_NODE_KEYWORD,
    0,
    "rule",
    "display rules",
    &cparser_node_show_root_mode,
    &cparser_node_show_root_rule_eol
};

cparser_node_t cparser_node_show_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode show",
    NULL,
    &cparser_node_show_root_rule
};

cparser_node_t cparser_node_show_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show,
    NULL,
    NULL,
    &cparser_node_show_root
};

cparser_node_t cparser_node_show = {
    CPARSER_NODE_KEYWORD,
    0,
    "show",
    "display stats, rule and mode",
    &cparser_node_clr,
    &cparser_node_show_eol
};

cparser_node_t cparser_node_cnfg_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_cnfg_exit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_cnfg_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    "exit from cnfg sub-context",
    NULL,
    &cparser_node_cnfg_root_exit_eol
};

cparser_node_t cparser_node_cnfg_root_clr_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_cnfg_clr,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_cnfg_root_clr = {
    CPARSER_NODE_KEYWORD,
    0,
    "clr ",
    "clear screen",
    &cparser_node_cnfg_root_exit,
    &cparser_node_cnfg_root_clr_eol
};

cparser_node_t cparser_node_cnfg_pact_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_pact_exit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_cnfg_pact_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit ",
    "exit from pact sub-context",
    NULL,
    &cparser_node_cnfg_pact_root_exit_eol
};

cparser_node_t cparser_node_cnfg_pact_root_clr_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_pact_clr,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_cnfg_pact_root_clr = {
    CPARSER_NODE_KEYWORD,
    0,
    "clr  ",
    "clear screen",
    &cparser_node_cnfg_pact_root_exit,
    &cparser_node_cnfg_pact_root_clr_eol
};

cparser_node_t cparser_node_pact_port4_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port4_exit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port4_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    "exit from port sub-context",
    NULL,
    &cparser_node_pact_port4_root_exit_eol
};

cparser_node_t cparser_node_pact_port4_root_clr_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port4_clr,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port4_root_clr = {
    CPARSER_NODE_KEYWORD,
    0,
    "clr ",
    "clear screen",
    &cparser_node_pact_port4_root_exit,
    &cparser_node_pact_port4_root_clr_eol
};

cparser_node_t cparser_node_pact_port4_root_st_st_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port4_st_st,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port4_root_st_st = {
    CPARSER_NODE_UINT,
    0,
    "0 - disable | 1 - enable",
    NULL,
    NULL,
    &cparser_node_pact_port4_root_st_st_eol
};

cparser_node_t cparser_node_pact_port4_root_st = {
    CPARSER_NODE_KEYWORD,
    0,
    "st  ",
    "set ST",
    &cparser_node_pact_port4_root_clr,
    &cparser_node_pact_port4_root_st_st
};

cparser_node_t cparser_node_pact_port4_root_acl_acl_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port4_acl_acl,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port4_root_acl_acl = {
    CPARSER_NODE_UINT,
    0,
    "0 - disable | 1 - enable",
    NULL,
    NULL,
    &cparser_node_pact_port4_root_acl_acl_eol
};

cparser_node_t cparser_node_pact_port4_root_acl = {
    CPARSER_NODE_KEYWORD,
    0,
    "acl ",
    "set acl operation",
    &cparser_node_pact_port4_root_st,
    &cparser_node_pact_port4_root_acl_acl
};

cparser_node_t cparser_node_pact_port4_root_drop_drp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port4_drop_drp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port4_root_drop_drp = {
    CPARSER_NODE_UINT,
    0,
    "0 - disable | 1 - enable",
    NULL,
    NULL,
    &cparser_node_pact_port4_root_drop_drp_eol
};

cparser_node_t cparser_node_pact_port4_root_drop = {
    CPARSER_NODE_KEYWORD,
    0,
    "drop",
    "set drop packet",
    &cparser_node_pact_port4_root_acl,
    &cparser_node_pact_port4_root_drop_drp
};

cparser_node_t cparser_node_pact_port4_root_fdrp_fdrp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port4_fdrp_fdrp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port4_root_fdrp_fdrp = {
    CPARSER_NODE_UINT,
    0,
    "0 - disable | 1 - enable",
    NULL,
    NULL,
    &cparser_node_pact_port4_root_fdrp_fdrp_eol
};

cparser_node_t cparser_node_pact_port4_root_fdrp = {
    CPARSER_NODE_KEYWORD,
    0,
    "fdrp",
    "set fragment drop",
    &cparser_node_pact_port4_root_drop,
    &cparser_node_pact_port4_root_fdrp_fdrp
};

cparser_node_t cparser_node_pact_port4_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode port4",
    NULL,
    &cparser_node_pact_port4_root_fdrp
};

cparser_node_t cparser_node_cnfg_pact_root_port4_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_pact_port4,
    NULL,
    NULL,
    &cparser_node_pact_port4_root
};

cparser_node_t cparser_node_cnfg_pact_root_port4 = {
    CPARSER_NODE_KEYWORD,
    0,
    "port4",
    "configure port4 action",
    &cparser_node_cnfg_pact_root_clr,
    &cparser_node_cnfg_pact_root_port4_eol
};

cparser_node_t cparser_node_pact_port3_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port3_exit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port3_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    "exit from port3 sub-context",
    NULL,
    &cparser_node_pact_port3_root_exit_eol
};

cparser_node_t cparser_node_pact_port3_root_clr_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port3_clr,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port3_root_clr = {
    CPARSER_NODE_KEYWORD,
    0,
    "clr ",
    "clear screen",
    &cparser_node_pact_port3_root_exit,
    &cparser_node_pact_port3_root_clr_eol
};

cparser_node_t cparser_node_pact_port3_root_st_st_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port3_st_st,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port3_root_st_st = {
    CPARSER_NODE_UINT,
    0,
    "0 - disable | 1 - enable",
    NULL,
    NULL,
    &cparser_node_pact_port3_root_st_st_eol
};

cparser_node_t cparser_node_pact_port3_root_st = {
    CPARSER_NODE_KEYWORD,
    0,
    "st  ",
    "set ST",
    &cparser_node_pact_port3_root_clr,
    &cparser_node_pact_port3_root_st_st
};

cparser_node_t cparser_node_pact_port3_root_acl_acl_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port3_acl_acl,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port3_root_acl_acl = {
    CPARSER_NODE_UINT,
    0,
    "0 - disable | 1 - enable",
    NULL,
    NULL,
    &cparser_node_pact_port3_root_acl_acl_eol
};

cparser_node_t cparser_node_pact_port3_root_acl = {
    CPARSER_NODE_KEYWORD,
    0,
    "acl ",
    "set acl operation",
    &cparser_node_pact_port3_root_st,
    &cparser_node_pact_port3_root_acl_acl
};

cparser_node_t cparser_node_pact_port3_root_drop_drp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port3_drop_drp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port3_root_drop_drp = {
    CPARSER_NODE_UINT,
    0,
    "0 - disable | 1 - enable",
    NULL,
    NULL,
    &cparser_node_pact_port3_root_drop_drp_eol
};

cparser_node_t cparser_node_pact_port3_root_drop = {
    CPARSER_NODE_KEYWORD,
    0,
    "drop",
    "set drop packet",
    &cparser_node_pact_port3_root_acl,
    &cparser_node_pact_port3_root_drop_drp
};

cparser_node_t cparser_node_pact_port3_root_fdrp_fdrp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port3_fdrp_fdrp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port3_root_fdrp_fdrp = {
    CPARSER_NODE_UINT,
    0,
    "0 - disable | 1 - enable",
    NULL,
    NULL,
    &cparser_node_pact_port3_root_fdrp_fdrp_eol
};

cparser_node_t cparser_node_pact_port3_root_fdrp = {
    CPARSER_NODE_KEYWORD,
    0,
    "fdrp",
    "set fragment drop",
    &cparser_node_pact_port3_root_drop,
    &cparser_node_pact_port3_root_fdrp_fdrp
};

cparser_node_t cparser_node_pact_port3_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode port3",
    NULL,
    &cparser_node_pact_port3_root_fdrp
};

cparser_node_t cparser_node_cnfg_pact_root_port3_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_pact_port3,
    NULL,
    NULL,
    &cparser_node_pact_port3_root
};

cparser_node_t cparser_node_cnfg_pact_root_port3 = {
    CPARSER_NODE_KEYWORD,
    0,
    "port3",
    "configure port3 action",
    &cparser_node_cnfg_pact_root_port4,
    &cparser_node_cnfg_pact_root_port3_eol
};

cparser_node_t cparser_node_pact_port2_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port2_exit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port2_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    "exit from port2 sub-context",
    NULL,
    &cparser_node_pact_port2_root_exit_eol
};

cparser_node_t cparser_node_pact_port2_root_clr_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port2_clr,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port2_root_clr = {
    CPARSER_NODE_KEYWORD,
    0,
    "clr ",
    "clear screen",
    &cparser_node_pact_port2_root_exit,
    &cparser_node_pact_port2_root_clr_eol
};

cparser_node_t cparser_node_pact_port2_root_st_st_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port2_st_st,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port2_root_st_st = {
    CPARSER_NODE_UINT,
    0,
    "0 - disable | 1 - enable",
    NULL,
    NULL,
    &cparser_node_pact_port2_root_st_st_eol
};

cparser_node_t cparser_node_pact_port2_root_st = {
    CPARSER_NODE_KEYWORD,
    0,
    "st  ",
    "set ST",
    &cparser_node_pact_port2_root_clr,
    &cparser_node_pact_port2_root_st_st
};

cparser_node_t cparser_node_pact_port2_root_acl_acl_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port2_acl_acl,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port2_root_acl_acl = {
    CPARSER_NODE_UINT,
    0,
    "0 - disable | 1 - enable",
    NULL,
    NULL,
    &cparser_node_pact_port2_root_acl_acl_eol
};

cparser_node_t cparser_node_pact_port2_root_acl = {
    CPARSER_NODE_KEYWORD,
    0,
    "acl ",
    "set acl operation",
    &cparser_node_pact_port2_root_st,
    &cparser_node_pact_port2_root_acl_acl
};

cparser_node_t cparser_node_pact_port2_root_drop_drp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port2_drop_drp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port2_root_drop_drp = {
    CPARSER_NODE_UINT,
    0,
    "0 - disable | 1 - enable",
    NULL,
    NULL,
    &cparser_node_pact_port2_root_drop_drp_eol
};

cparser_node_t cparser_node_pact_port2_root_drop = {
    CPARSER_NODE_KEYWORD,
    0,
    "drop",
    "set drop packet",
    &cparser_node_pact_port2_root_acl,
    &cparser_node_pact_port2_root_drop_drp
};

cparser_node_t cparser_node_pact_port2_root_fdrp_fdrp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port2_fdrp_fdrp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port2_root_fdrp_fdrp = {
    CPARSER_NODE_UINT,
    0,
    "0 - disable | 1 - enable",
    NULL,
    NULL,
    &cparser_node_pact_port2_root_fdrp_fdrp_eol
};

cparser_node_t cparser_node_pact_port2_root_fdrp = {
    CPARSER_NODE_KEYWORD,
    0,
    "fdrp",
    "set fragment drop",
    &cparser_node_pact_port2_root_drop,
    &cparser_node_pact_port2_root_fdrp_fdrp
};

cparser_node_t cparser_node_pact_port2_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode port2",
    NULL,
    &cparser_node_pact_port2_root_fdrp
};

cparser_node_t cparser_node_cnfg_pact_root_port2_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_pact_port2,
    NULL,
    NULL,
    &cparser_node_pact_port2_root
};

cparser_node_t cparser_node_cnfg_pact_root_port2 = {
    CPARSER_NODE_KEYWORD,
    0,
    "port2",
    "configure port2 action",
    &cparser_node_cnfg_pact_root_port3,
    &cparser_node_cnfg_pact_root_port2_eol
};

cparser_node_t cparser_node_pact_port1_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port1_exit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port1_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    "exit from port1 sub-context",
    NULL,
    &cparser_node_pact_port1_root_exit_eol
};

cparser_node_t cparser_node_pact_port1_root_clr_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port1_clr,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port1_root_clr = {
    CPARSER_NODE_KEYWORD,
    0,
    "clr ",
    "clear screen",
    &cparser_node_pact_port1_root_exit,
    &cparser_node_pact_port1_root_clr_eol
};

cparser_node_t cparser_node_pact_port1_root_st_st_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port1_st_st,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port1_root_st_st = {
    CPARSER_NODE_UINT,
    0,
    "0 - disable | 1 - enable",
    NULL,
    NULL,
    &cparser_node_pact_port1_root_st_st_eol
};

cparser_node_t cparser_node_pact_port1_root_st = {
    CPARSER_NODE_KEYWORD,
    0,
    "st  ",
    "set ST",
    &cparser_node_pact_port1_root_clr,
    &cparser_node_pact_port1_root_st_st
};

cparser_node_t cparser_node_pact_port1_root_acl_acl_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port1_acl_acl,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port1_root_acl_acl = {
    CPARSER_NODE_UINT,
    0,
     "0 - disable | 1 - enable",
    NULL,
    NULL,
    &cparser_node_pact_port1_root_acl_acl_eol
};

cparser_node_t cparser_node_pact_port1_root_acl = {
    CPARSER_NODE_KEYWORD,
    0,
    "acl ",
    "set acl operation",
    &cparser_node_pact_port1_root_st,
    &cparser_node_pact_port1_root_acl_acl
};

cparser_node_t cparser_node_pact_port1_root_drop_drp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port1_drop_drp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port1_root_drop_drp = {
    CPARSER_NODE_UINT,
    0,
    "0 - disable | 1 - enable",
    NULL,
    NULL,
    &cparser_node_pact_port1_root_drop_drp_eol
};

cparser_node_t cparser_node_pact_port1_root_drop = {
    CPARSER_NODE_KEYWORD,
    0,
    "drop",
    "set drop packets",
    &cparser_node_pact_port1_root_acl,
    &cparser_node_pact_port1_root_drop_drp
};

cparser_node_t cparser_node_pact_port1_root_fdrp_fdrp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_port1_fdrp_fdrp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_pact_port1_root_fdrp_fdrp = {
    CPARSER_NODE_UINT,
    0,
    "0 - disable | 1 - enable",
    NULL,
    NULL,
    &cparser_node_pact_port1_root_fdrp_fdrp_eol
};

cparser_node_t cparser_node_pact_port1_root_fdrp = {
    CPARSER_NODE_KEYWORD,
    0,
    "fdrp",
    "set fragment drop",
    &cparser_node_pact_port1_root_drop,
    &cparser_node_pact_port1_root_fdrp_fdrp
};

cparser_node_t cparser_node_pact_port1_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode port1",
    NULL,
    &cparser_node_pact_port1_root_fdrp
};

cparser_node_t cparser_node_cnfg_pact_root_port1_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_pact_port1,
    NULL,
    NULL,
    &cparser_node_pact_port1_root
};

cparser_node_t cparser_node_cnfg_pact_root_port1 = {
    CPARSER_NODE_KEYWORD,
    0,
    "port1",
    "configure port1 action",
    &cparser_node_cnfg_pact_root_port2,
    &cparser_node_cnfg_pact_root_port1_eol
};

cparser_node_t cparser_node_cnfg_pact_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode pact",
    NULL,
    &cparser_node_cnfg_pact_root_port1
};

cparser_node_t cparser_node_cnfg_root_pact_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_cnfg_pact,
    NULL,
    NULL,
    &cparser_node_cnfg_pact_root
};

cparser_node_t cparser_node_cnfg_root_pact = {
    CPARSER_NODE_KEYWORD,
    0,
    "pact",
    "port action",
    &cparser_node_cnfg_root_clr,
    &cparser_node_cnfg_root_pact_eol
};

cparser_node_t cparser_node_cnfg_root_port_ingress_port_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_cnfg_port_ingress_port,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_cnfg_root_port_ingress_port = {
    CPARSER_NODE_UINT,
    0,
    "port1 - 1| port2 -2 | port3 -3 |port4 -4 | drop - 255",
    NULL,
    NULL,
    &cparser_node_cnfg_root_port_ingress_port_eol
};

cparser_list_node_t cparser_list_node_cnfg_root_port_ingress_4 = {
    NULL,
    "4"
 };

cparser_list_node_t cparser_list_node_cnfg_root_port_ingress_3 = {
    &cparser_list_node_cnfg_root_port_ingress_4,
    "3"
 };

cparser_list_node_t cparser_list_node_cnfg_root_port_ingress_2 = {
    &cparser_list_node_cnfg_root_port_ingress_3,
    "2"
 };

cparser_list_node_t cparser_list_node_cnfg_root_port_ingress_1 = {
    &cparser_list_node_cnfg_root_port_ingress_2,
    "1"
 };

cparser_node_t cparser_node_cnfg_root_port_ingress = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_cnfg_root_port_ingress_1,
    NULL,
    NULL,
    &cparser_node_cnfg_root_port_ingress_port
};

cparser_node_t cparser_node_cnfg_root_port = {
    CPARSER_NODE_KEYWORD,
    0,
    "port",
    "configure port map",
    &cparser_node_cnfg_root_pact,
    &cparser_node_cnfg_root_port_ingress
};

cparser_node_t cparser_node_cnfg_root_mode_mode_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_cnfg_mode_mode,
    NULL,
    NULL,
    NULL
};

cparser_list_node_t cparser_list_node_cnfg_root_mode_mode_intercept = {
    NULL,
    "intercept"
 };

cparser_list_node_t cparser_list_node_cnfg_root_mode_mode_bypass = {
    &cparser_list_node_cnfg_root_mode_mode_intercept,
    "bypass"
 };

cparser_node_t cparser_node_cnfg_root_mode_mode = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_cnfg_root_mode_mode_bypass,
    NULL,
    NULL,
    &cparser_node_cnfg_root_mode_mode_eol
};

cparser_node_t cparser_node_cnfg_root_mode = {
    CPARSER_NODE_KEYWORD,
    0,
    "mode",
    "select mode",
    &cparser_node_cnfg_root_port,
    &cparser_node_cnfg_root_mode_mode
};

cparser_node_t cparser_node_cnfg_rule_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_rule_exit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_cnfg_rule_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    "exit from rule sub-context",
    NULL,
    &cparser_node_cnfg_rule_root_exit_eol
};

cparser_node_t cparser_node_cnfg_rule_root_clr_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_rule_clr,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_cnfg_rule_root_clr = {
    CPARSER_NODE_KEYWORD,
    0,
    "clr ",
    "clear screen",
    &cparser_node_cnfg_rule_root_exit,
    &cparser_node_cnfg_rule_root_clr_eol
};

cparser_node_t cparser_node_cnfg_rule_root_del_version_proto_rule_num_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_rule_del_version_proto_rule_num,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_cnfg_rule_root_del_version_proto_rule_num = {
    CPARSER_NODE_UINT,
    0,
    "Rule number",
    NULL,
    NULL,
    &cparser_node_cnfg_rule_root_del_version_proto_rule_num_eol
};

cparser_list_node_t cparser_list_node_cnfg_rule_root_del_version_proto_dcerpc = {
    NULL,
    "dcerpc"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_del_version_proto_smb2 = {
    &cparser_list_node_cnfg_rule_root_del_version_proto_dcerpc,
    "smb2"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_del_version_proto_smb = {
    &cparser_list_node_cnfg_rule_root_del_version_proto_smb2,
    "smb"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_del_version_proto_dns = {
    &cparser_list_node_cnfg_rule_root_del_version_proto_smb,
    "dns"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_del_version_proto_smtp = {
    &cparser_list_node_cnfg_rule_root_del_version_proto_dns,
    "smtp"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_del_version_proto_sctp = {
    &cparser_list_node_cnfg_rule_root_del_version_proto_smtp,
    "sctp"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_del_version_proto_ftp = {
    &cparser_list_node_cnfg_rule_root_del_version_proto_sctp,
    "ftp"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_del_version_proto_gtp = {
    &cparser_list_node_cnfg_rule_root_del_version_proto_ftp,
    "gtp"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_del_version_proto_gre = {
    &cparser_list_node_cnfg_rule_root_del_version_proto_gtp,
    "gre"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_del_version_proto_tls = {
    &cparser_list_node_cnfg_rule_root_del_version_proto_gre,
    "tls"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_del_version_proto_http = {
    &cparser_list_node_cnfg_rule_root_del_version_proto_tls,
    "http"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_del_version_proto_icmp = {
    &cparser_list_node_cnfg_rule_root_del_version_proto_http,
    "icmp"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_del_version_proto_ssl = {
    &cparser_list_node_cnfg_rule_root_del_version_proto_icmp,
    "ssl"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_del_version_proto_udp = {
    &cparser_list_node_cnfg_rule_root_del_version_proto_ssl,
    "udp"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_del_version_proto_tcp = {
    &cparser_list_node_cnfg_rule_root_del_version_proto_udp,
    "tcp"
 };

cparser_node_t cparser_node_cnfg_rule_root_del_version_proto = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_cnfg_rule_root_del_version_proto_tcp,
    NULL,
    NULL,
    &cparser_node_cnfg_rule_root_del_version_proto_rule_num
};

cparser_list_node_t cparser_list_node_cnfg_rule_root_del_version_ipv6 = {
    NULL,
    "ipv6"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_del_version_ipv4 = {
    &cparser_list_node_cnfg_rule_root_del_version_ipv6,
    "ipv4"
 };

cparser_node_t cparser_node_cnfg_rule_root_del_version = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_cnfg_rule_root_del_version_ipv4,
    NULL,
    NULL,
    &cparser_node_cnfg_rule_root_del_version_proto
};

cparser_node_t cparser_node_cnfg_rule_root_del = {
    CPARSER_NODE_KEYWORD,
    0,
    "del ",
    "delete rule",
    &cparser_node_cnfg_rule_root_clr,
    &cparser_node_cnfg_rule_root_del_version
};

cparser_node_t cparser_node_rule_lst_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_lst_exit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule_lst_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit  ",
    "exit from list sub-context",
    NULL,
    &cparser_node_rule_lst_root_exit_eol
};

cparser_node_t cparser_node_rule_lst_root_clr_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_lst_clr,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule_lst_root_clr = {
    CPARSER_NODE_KEYWORD,
    0,
    "clr   ",
    "clear screen",
    &cparser_node_rule_lst_root_exit,
    &cparser_node_rule_lst_root_clr_eol
};

cparser_node_t cparser_node_rule_lst_root_dcerpc_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_lst_dcerpc,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule_lst_root_dcerpc = {
    CPARSER_NODE_KEYWORD,
    0,
    "dcerpc",
    "list dcerpc rules",
    &cparser_node_rule_lst_root_clr,
    &cparser_node_rule_lst_root_dcerpc_eol
};

cparser_node_t cparser_node_rule_lst_root_smb2_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_lst_smb2,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule_lst_root_smb2 = {
    CPARSER_NODE_KEYWORD,
    0,
    "smb2  ",
    "list smp rules",
    &cparser_node_rule_lst_root_dcerpc,
    &cparser_node_rule_lst_root_smb2_eol
};

cparser_node_t cparser_node_rule_lst_root_smb_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_lst_smb,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule_lst_root_smb = {
    CPARSER_NODE_KEYWORD,
    0,
    "smb",
    NULL,
    &cparser_node_rule_lst_root_smb2,
    &cparser_node_rule_lst_root_smb_eol
};

cparser_node_t cparser_node_rule_lst_root_dns_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_lst_dns,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule_lst_root_dns = {
    CPARSER_NODE_KEYWORD,
    0,
    "dns   ",
    "list dns rules",
    &cparser_node_rule_lst_root_smb,
    &cparser_node_rule_lst_root_dns_eol
};

cparser_node_t cparser_node_rule_lst_root_smtp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_lst_smtp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule_lst_root_smtp = {
    CPARSER_NODE_KEYWORD,
    0,
    "smtp  ",
    "list smtp rules",
    &cparser_node_rule_lst_root_dns,
    &cparser_node_rule_lst_root_smtp_eol
};

cparser_node_t cparser_node_rule_lst_root_sctp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_lst_sctp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule_lst_root_sctp = {
    CPARSER_NODE_KEYWORD,
    0,
    "sctp  ",
    "list sctp rules",
    &cparser_node_rule_lst_root_smtp,
    &cparser_node_rule_lst_root_sctp_eol
};

cparser_node_t cparser_node_rule_lst_root_ftp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_lst_ftp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule_lst_root_ftp = {
    CPARSER_NODE_KEYWORD,
    0,
    "ftp   ",
    "list ftp rules",
    &cparser_node_rule_lst_root_sctp,
    &cparser_node_rule_lst_root_ftp_eol
};

cparser_node_t cparser_node_rule_lst_root_gtp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_lst_gtp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule_lst_root_gtp = {
    CPARSER_NODE_KEYWORD,
    0,
    "gtp   ",
    "list gtp rules",
    &cparser_node_rule_lst_root_ftp,
    &cparser_node_rule_lst_root_gtp_eol
};

cparser_node_t cparser_node_rule_lst_root_gre_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_lst_gre,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule_lst_root_gre = {
    CPARSER_NODE_KEYWORD,
    0,
    "gre   ",
    "list gre rules",
    &cparser_node_rule_lst_root_gtp,
    &cparser_node_rule_lst_root_gre_eol
};

cparser_node_t cparser_node_rule_lst_root_tls_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_lst_tls,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule_lst_root_tls = {
    CPARSER_NODE_KEYWORD,
    0,
    "tls   ",
    "list tls rules",
    &cparser_node_rule_lst_root_gre,
    &cparser_node_rule_lst_root_tls_eol
};

cparser_node_t cparser_node_rule_lst_root_http_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_lst_http,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule_lst_root_http = {
    CPARSER_NODE_KEYWORD,
    0,
    "http  ",
    "list http rules",
    &cparser_node_rule_lst_root_tls,
    &cparser_node_rule_lst_root_http_eol
};

cparser_node_t cparser_node_rule_lst_root_icmp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_lst_icmp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule_lst_root_icmp = {
    CPARSER_NODE_KEYWORD,
    0,
    "icmp  ",
    "list icmp rules",
    &cparser_node_rule_lst_root_http,
    &cparser_node_rule_lst_root_icmp_eol
};

cparser_node_t cparser_node_rule_lst_root_ssl_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_lst_ssl,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule_lst_root_ssl = {
    CPARSER_NODE_KEYWORD,
    0,
    "ssl   ",
    "list rules",
    &cparser_node_rule_lst_root_icmp,
    &cparser_node_rule_lst_root_ssl_eol
};

cparser_node_t cparser_node_rule_lst_root_udp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_lst_udp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule_lst_root_udp = {
    CPARSER_NODE_KEYWORD,
    0,
    "udp   ",
    "list udp rules",
    &cparser_node_rule_lst_root_ssl,
    &cparser_node_rule_lst_root_udp_eol
};

cparser_node_t cparser_node_rule_lst_root_tcp_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_lst_tcp,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_rule_lst_root_tcp = {
    CPARSER_NODE_KEYWORD,
    0,
    "tcp   ",
    "list tcp rules",
    &cparser_node_rule_lst_root_udp,
    &cparser_node_rule_lst_root_tcp_eol
};

cparser_node_t cparser_node_rule_lst_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode lst",
    NULL,
    &cparser_node_rule_lst_root_tcp
};

cparser_node_t cparser_node_cnfg_rule_root_lst_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_rule_lst,
    NULL,
    NULL,
    &cparser_node_rule_lst_root
};

cparser_node_t cparser_node_cnfg_rule_root_lst = {
    CPARSER_NODE_KEYWORD,
    0,
    "lst ",
    "list rules",
    &cparser_node_cnfg_rule_root_del,
    &cparser_node_cnfg_rule_root_lst_eol
};

cparser_node_t cparser_node_cnfg_rule_root_add_action_version_proto_sip_sprt_direction_dip_dprt_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_rule_add_action_version_proto_sip_sprt_direction_dip_dprt,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_cnfg_rule_root_add_action_version_proto_sip_sprt_direction_dip_dprt = {
    CPARSER_NODE_UINT,
    0,
    "Destination port",
    "port 0 means any port",
    NULL,
    &cparser_node_cnfg_rule_root_add_action_version_proto_sip_sprt_direction_dip_dprt_eol
};

cparser_node_t cparser_node_cnfg_rule_root_add_action_version_proto_sip_sprt_direction_dip = {
    CPARSER_NODE_IPV4ADDR,
    0,
    "Destination ip",
    "ip 0.0.0.0 means any ip",
    NULL,
    &cparser_node_cnfg_rule_root_add_action_version_proto_sip_sprt_direction_dip_dprt
};

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_proto_sip_sprt_direction_both = {
    NULL,
    "both"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_proto_sip_sprt_direction_w2l = {
    &cparser_list_node_cnfg_rule_root_add_action_version_proto_sip_sprt_direction_both,
    "w2l"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_proto_sip_sprt_direction_l2w = {
    &cparser_list_node_cnfg_rule_root_add_action_version_proto_sip_sprt_direction_w2l,
    "l2w"
 };

cparser_node_t cparser_node_cnfg_rule_root_add_action_version_proto_sip_sprt_direction = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_cnfg_rule_root_add_action_version_proto_sip_sprt_direction_l2w,
    NULL,
    NULL,
    &cparser_node_cnfg_rule_root_add_action_version_proto_sip_sprt_direction_dip
};

cparser_node_t cparser_node_cnfg_rule_root_add_action_version_proto_sip_sprt = {
    CPARSER_NODE_UINT,
    0,
    "Source port",
    "port0 means any port",
    NULL,
    &cparser_node_cnfg_rule_root_add_action_version_proto_sip_sprt_direction
};

cparser_node_t cparser_node_cnfg_rule_root_add_action_version_proto_sip = {
    CPARSER_NODE_IPV4ADDR,
    0,
    "Source ip",
    "ip 0.0.0.0 means any ip",
    NULL,
    &cparser_node_cnfg_rule_root_add_action_version_proto_sip_sprt
};

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_proto_dcerpc = {
    NULL,
    "dcerpc"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_proto_smb2 = {
    &cparser_list_node_cnfg_rule_root_add_action_version_proto_dcerpc,
    "smb2"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_proto_smb = {
    &cparser_list_node_cnfg_rule_root_add_action_version_proto_smb2,
    "smb"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_proto_dns = {
    &cparser_list_node_cnfg_rule_root_add_action_version_proto_smb,
    "dns"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_proto_smtp = {
    &cparser_list_node_cnfg_rule_root_add_action_version_proto_dns,
    "smtp"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_proto_sctp = {
    &cparser_list_node_cnfg_rule_root_add_action_version_proto_smtp,
    "sctp"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_proto_ftp = {
    &cparser_list_node_cnfg_rule_root_add_action_version_proto_sctp,
    "ftp"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_proto_gtp = {
    &cparser_list_node_cnfg_rule_root_add_action_version_proto_ftp,
    "gtp"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_proto_gre = {
    &cparser_list_node_cnfg_rule_root_add_action_version_proto_gtp,
    "gre"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_proto_tls = {
    &cparser_list_node_cnfg_rule_root_add_action_version_proto_gre,
    "tls"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_proto_ssl = {
    &cparser_list_node_cnfg_rule_root_add_action_version_proto_tls,
    "ssl"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_proto_http = {
    &cparser_list_node_cnfg_rule_root_add_action_version_proto_ssl,
    "http"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_proto_icmp = {
    &cparser_list_node_cnfg_rule_root_add_action_version_proto_http,
    "icmp"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_proto_udp = {
    &cparser_list_node_cnfg_rule_root_add_action_version_proto_icmp,
    "udp"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_proto_tcp = {
    &cparser_list_node_cnfg_rule_root_add_action_version_proto_udp,
    "tcp"
 };

cparser_node_t cparser_node_cnfg_rule_root_add_action_version_proto = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_cnfg_rule_root_add_action_version_proto_tcp,
    NULL,
    NULL,
    &cparser_node_cnfg_rule_root_add_action_version_proto_sip
};

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_ipv6 = {
    NULL,
    "ipv6"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_version_ipv4 = {
    &cparser_list_node_cnfg_rule_root_add_action_version_ipv6,
    "ipv4"
 };

cparser_node_t cparser_node_cnfg_rule_root_add_action_version = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_cnfg_rule_root_add_action_version_ipv4,
    NULL,
    NULL,
    &cparser_node_cnfg_rule_root_add_action_version_proto
};

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_reject = {
    NULL,
    "reject"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_drop = {
    &cparser_list_node_cnfg_rule_root_add_action_reject,
    "drop"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_pass = {
    &cparser_list_node_cnfg_rule_root_add_action_drop,
    "pass"
 };

cparser_list_node_t cparser_list_node_cnfg_rule_root_add_action_alert = {
    &cparser_list_node_cnfg_rule_root_add_action_pass,
    "alert"
 };

cparser_node_t cparser_node_cnfg_rule_root_add_action = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_cnfg_rule_root_add_action_alert,
    NULL,
    NULL,
    &cparser_node_cnfg_rule_root_add_action_version
};

cparser_node_t cparser_node_cnfg_rule_root_add = {
    CPARSER_NODE_KEYWORD,
    0,
    "add ",
    "add rules",
    &cparser_node_cnfg_rule_root_lst,
    &cparser_node_cnfg_rule_root_add_action
};

cparser_node_t cparser_node_cnfg_rule_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode rule",
    NULL,
    &cparser_node_cnfg_rule_root_add
};

cparser_node_t cparser_node_cnfg_root_rule_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_cnfg_rule,
    NULL,
    NULL,
    &cparser_node_cnfg_rule_root
};

cparser_node_t cparser_node_cnfg_root_rule = {
    CPARSER_NODE_KEYWORD,
    0,
    "rule",
    "config rule",
    &cparser_node_cnfg_root_mode,
    &cparser_node_cnfg_root_rule_eol
};

cparser_node_t cparser_node_cnfg_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode cnfg",
    NULL,
    &cparser_node_cnfg_root_rule
};

cparser_node_t cparser_node_cnfg_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_cnfg,
    "to configure rules andmode",
    NULL,
    &cparser_node_cnfg_root
};

cparser_node_t cparser_node_cnfg = {
    CPARSER_NODE_KEYWORD,
    0,
    "cnfg",
    "config rule, port and mode",
    &cparser_node_show,
    &cparser_node_cnfg_eol
};

cparser_node_t cparser_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root node of the parser tree",
    NULL,
    &cparser_node_cnfg
};

